### ISSUE TITLE
JSON-LD is missing

### ISSUE THREAD

**Issue by akuckartz** [dret/hypermedia#4]

**Comment by dret** [comment]
JSON-LD isn't a hypermedia format. it's simply databinding between JSON and RDF, and the latter isn't hypermedia either. or would you disagree with that?

**Comment by Conal-Tuohy** [comment]
The idea that JSON-LD is not a hypermedia format seems very odd to me. 

It's hard to square with the description of JSON-LD on JSON-LD.org:
"It allows an application to start at one piece of Linked Data, and follow embedded links to other pieces of Linked Data that are hosted on different sites across the Web."
What is that if not hypermedia?

Or see the W3 Hydra Community group which is all about "hypermedia-driven" Web APIs and includes JSON-LD (along with Turtle) as examples of such formats. https://www.w3.org/community/hydra/

My personal opinion is that all "Linked Data" formats are correctly seen as hypermedia data formats (i.e. hyperdata). That would include JSON-LD and other RDF serializations as well. 

Of course RDF is sometimes used outside of a hypermedia context, purely as a graph model for KR, that just happens to use IRIs as node identifiers, but where RDF serializations are used as Linked Data formats, carrying URIs which clients can use to make HTTP requests for related data (the "follow your nose" principle), then that is hypermedia.

The fact that they can also be used purely as a graph serialization is not a solid counter argument. After all, SVG is often used purely for drawing pictures to be printed on paper, but that doesn't mean it's not also a hypermedia format.

**Comment by dret** [comment]
On 2015-09-15 06:29, Conal Tuohy wrote:

> The idea that JSON-LD is not a hypermedia format seems very odd to me.
> It's hard to square with the description of JSON-LD on JSON-LD.org:
> "It allows an application to start at one piece of Linked Data, and
> follow embedded links to other pieces of Linked Data that are hosted on
> different sites across the Web."
> What is that if not hypermedia?

it's one thing to read the sales pitch, and another thing what the  pitched technology is actually doing. JSON-LD is databinding from JSON  to RDF, that's all. iff it's used to map into a RDF model that's  actually hypermedia (and not just some RDF graph), then you're right.  but that's something that JSON-LD is not concerned with.

> Or see the W3 Hydra Community group which is all about
> "hypermedia-driven" Web APIs and includes JSON-LD (along with Turtle) as
> examples of such formats. https://www.w3.org/community/hydra/

now that's different because hydra actually defines a vocabulary that's  hypermedia. which is why it is listed as a format in hyperpedia.

if JSON-LD is used to map some JSON into hydra RDF, then the result  indeed is hypermedia, but that's because of hydra, not because of JSON-LD.

this is my attempt at explaining the reason why so far i have decided to  keep JSON-LD out of the list. if we included it, we would arguably have  to include XSLT and other transformation languages as well, because all  of these _can_ be used to transform some source model into a target  model that's hypermedia.

> My personal opinion is that all "Linked Data" formats are correctly seen
> as hypermedia data formats (i.e. hyperdata). That would include JSON-LD
> and other RDF serializations as well.

but then we would need to include XML and JSON and other formats as  well, because these, like RDF, often are used to represent linked data,  even though they are not themselves the foundational model, right?

(and yes, i have included XML, but not because of the XML models that  may be hypermedia in nature, but because of the very limited linking  that is built into XML itself).

> Of course RDF is sometimes used outside of a hypermedia context, purely
> as a graph model for KR, that just happens to use IRIs as node
> identifiers, but where RDF serializations are used as Linked Data
> formats, carrying URIs which clients can use to make HTTP requests for
> related data (the "follow your nose" principle), then that is hypermedia.

yes, i agree to that. but that does not mean that RDF is the hypermedia.  what establishes the hypermedianess in these cases are vocabularies,  such as hydra. those and their semantics are the foundations for your  RDF being hypermedia, not the fact that your model is based on the RDF  metamodel

it's the very same as with XML/SGML: there are many hypermedia  vocabularies that people use and then serialize it as XML/SGML, but that  does not mean that the metamodel, the XML/SGML, is hypermedia. what's  making their formats hypermedia are the models they are using, such as  HTML or Atom or XForms.

> The fact that they can also be used purely as a graph serialization is
> not a solid counter argument. After all, SVG is often used purely for
> drawing pictures to be printed on paper, but that doesn't mean it's not
> also a hypermedia format.

it's of course not a question of what a language is used for in single  examples. but it's the question whether the language has hypermedia  features to begin with. RDF has none. SVG has them  (http://www.w3.org/TR/SVG/linking.html). so RDF isn't hypermedia, and  SVG is.

and many thanks for mentioning SVG, i just added it to the list!

**Comment by Conal-Tuohy** [comment]
It's not clear to me what the scope of your hyperpedia is - what is a "hypermedia format"? Is it an abstract data model or vocabulary? Is it a serialization or content type? My assumption was that you were talking about serializations, and therefore that any serialization which was in practice used as hypermedia, would be fair game. So that would include any RDF serializations used in Linked Data systems. This is in fact what I came to hyperpedia looking for. I'm happy to keep looking elsewhere for the information I need, but I do think that you should be clearer about what "hypermedia" means for you, and what a "hypermedia format" is, and say why Linked Data formats are out of scope for you.

Apparently you are excluding everything RDF because the "hypermedia" features you're looking for are provided by specific RDF vocabularies rather than by the RDF model itself? Given that many RDF vocabularies do deal with hyperlinks as pointers to resources (I'm struggling to see what counts as "hypermedia" for you, so this is a guess), does that make all of those vocabularies themselves "hypermedia" and hence eligible for inclusion? e.g. http://www.w3.org/TR/void/ or even FOAF?

In any case, though, I think the idea that "generic" RDF is not hypermedia is factually mistaken, as there are numerous software products in deployment on the web today which do publish RDF graphs to generic clients, which in turn extract URIs and make further requests, navigating a web of data. This is what Linked Data is all about, and it's a practice that's not tied to any specific RDF vocabulary, schema, or ontology.

**Comment by dret** [comment]
On 2015-09-16 03:00, Conal Tuohy wrote:

> It's not clear to me what the scope of your hyperpedia is - what is a
> "hypermedia format"? Is it an abstract data model or vocabulary? Is it a
> serialization or content type? My assumption was that you were talking
> about serializations, and therefore that any serialization which was in
> practice used as hypermedia, would be fair game. So that would include
> any RDF serializations used in Linked Data systems. This is in fact what
> I came to hyperpedia looking for. I'm happy to keep looking elsewhere
> for the information I need, but I do think that you be clear about what
> "hypermedia" is, and what a "hypermedia format" is, and say why Linked
> Data formats are out of scope for you.

they are not out of scope, i hope i did not say that anywhere. if they 
do have actual link models (such as hydra, which is in the list of 
formats), then they're hypermedia. but hypermedia is more than just a 
graph-based data model, that's all.

you certainly are right, though, that the term "hypermedia format" might 
be less that great, and might need some definition. in the end what 
matters is a model, of course, but a model without a representation is 
meaningless in distributed systems. so what matters, for example, is 
hydra's "link model", and the fact that RDF happens to have various 
serializations really is of no consequence.

> Apparently you are excluding everything RDF because the "hypermedia"
> features you're looking for are provided by specific RDF vocabularies
> rather than by the RDF model itself? Given that many RDF vocabularies do
> deal with hyperlinks as pointers to resources (I'm struggling to see
> what counts as "hypermedia" for you, so this is a guess), does that make
> those vocabularies themselves "hypermedia" and hence eligible for
> inclusion?

there currently is a separation into "Generic/Modular Formats" and 
"Specific/Application Formats". that may not be a great separation, but 
that's what's currently there. hydra is listed as generic (because it's 
likely that applications will mix-in there own vocabularies), whereas 
HTML is listed as specific (because applications usually just use HTML 
and nothing else). but this distinction is hard to hold up, and maybe it 
should go away entirely.

of course you could describe any format as "hypermedia" that has 
meaningful links, where applications are build on the principle of 
following links to achieve application goals. that might yield very many 
(too many) entries. but the intention isn't that this should become a 
complete directory of all models/formats that use links.

instead, it started out of questions in the W3C DWBP group where people 
said "tell me more about this hypermedia thing". it is an attempt to 
look at certain dimensions of the hypermedia spectrum, and then maybe 
some existing models/formats could be used to demonstrate those 
dimensions, so that people can see why they might be useful to have (or 
not interesting for their scenarios).

> In any case, though, I think the idea that "generic" RDF is not
> hypermedia is factually mistaken, as there are numerous software
> products in deployment on the web today which do publish RDF graphs to
> generic clients, which in turn extract URIs and make further requests,
> navigating a web of data. This is what Linked Data is all about, and
> it's not tied to any specific RDF vocabulary, schema, or ontology.

hypermedia is more than using identifiers to crawl a graph model that is 
available in a distributed fashion. the "web of data" or (the name 
before that) "giant global graph" is just that: a graph that can be 
traversed for the purpose of crawling it (if that's what you want to do).

**Comment by asbjornu** [comment]
I'd say any format that promotes the URI to a first class citizen deserves a mention. Even though the URI is "just" used to build a graph in JSON-LD, that's way more than one can say of most of the Web APIs created today, which leak internal object models such as non-dereferenceable database identifiers meant to be used by the client to build a hard coded URI in order to perform the next request.

I think just using URIs as identifiers is novel and valuable enough by itself, which is why I think JSON-LD deserves a mention as a hypermedia format.

**Comment by dret** [comment]
On 2017-01-31 17:30, Asbjørn Ulsberg wrote:
> I'd say any format that promotes the URI to a first class citizen
> deserves a mention. Even though the URI is "just" used to build a graph
> in JSON-LD, that's way more than one can say of most of the Web APIs
> created today, which leak internal object models such as
> non-dereferenceable database identifiers meant to be used by the client
> to build a hard coded URI in order to perform the next request.

well, this gets us down the well-known rabbit hole of discussing whether 
RDF is hypermedia or not (because JSON-LD is nothing but a serialization 
of RDF). i have RDF spec editors on record saying that it is not, and i 
am of the same opinion. but this is not something we should try to 
settle here.

> I think just using URIs as identifiers is novel and valuable enough by
> itself, which is why I think JSON-LD deserves a mention as a hypermedia
> format.

hypermedia specifically is about links, not about using a specific data 
type to build up a graph-based model. but as i said, this is something 
i'd be more than happy to discuss next time we meet.

to me, the main issue is that if JSON-LD gets added, then it will have 
zero of the features listed in hyperpedia (because it has no links as a 
consequence of not being hypermedia). wouldn't that be rather odd?

**Comment by asbjornu** [comment]
> to me, the main issue is that if JSON-LD gets added, then it will have zero of the features listed in hyperpedia (because it has no links as a consequence of not being hypermedia). wouldn't that be rather odd?

I would find that odd if I agreed with you. 😄  But the way I see it, **JSON-LD most definitely has links**.

JSON-LD standardises the `@id` keyword. It would have done that in one way or another regardless of its RDF foundation, seeing how the RDF foundation of JSON-LD was built after the fact and not a design goal from the start. @msporny's blog post on [the origins of JSON-LD](http://manu.sporny.org/2014/json-ld-origins-2/) explains this in great detail.

My view is that JSON-LD makes a lot of sense for people who are wholly uninterested in RDF. Just having a way to convey that something is a URI is a core part of what makes any format into a hypermedia format, imho, and is valuable enough in and of itself.

That JSON-LD builds on RDF and makes an API described with it a part of the Semantic Web and whatnot is a bonus most users of JSON-LD shouldn't and won't have to know anything about.

**Comment by msporny** [comment]
> JSON-LD most definitely has links

@dret, I'm having a hard time understanding this thread possibly because I can't see a proper definition of "hypermedia". The assertion that JSON-LD doesn't have links is also problematic; I would say it does.

Remember that the JSON-LD data model was not based on RDF initially, and still goes beyond RDF, we just adopted the bits of RDF that were effectively being re-invented in JSON-LD:

http://json-ld.org/spec/latest/json-ld/#data-model

In any case, links are a first-class concept in JSON-LD... with or without pulling in the RDF bits (JSON-LD has its own data model, and links are a part of that data model).

**Comment by dret** [comment]
On 2017-01-31 20:41, Manu Sporny wrote:
>     JSON-LD most definitely has links
> @dret <https://github.com/dret>, I'm having a hard time understanding
> this thread possibly because I can't see a proper 'definition' of
> hypermedia.

fair point. https://github.com/dret/hyperpedia/commit/9b20f4dc804de54378f0beb97a8e41aebe1c1ec7 (adding https://github.com/dret/hyperpedia/blob/master/hypermedia-definition.md) is a first proposal.

> The assertion that JSON-LD doesn't have links is also
> problematic; I would say it does.

could you give an example, please? i am still struggling to see that.

**Comment by asbjornu** [comment]
@msporny: I think @dret has a point. If `@id` can't be guaranteed to be dereferenceable (the specification say `SHOULD`, not `MUST`), it isn't really a link, is it? The following is, to the best of my knowledge, a perfectly valid JSON-LD document, but doesn't link to anywhere:

```json
{
  "@context": {
    "foo": {
      "@id": "urn:foo",
      "@type": "@id"
    }
  },
  "foo": "urn:bar"
}
```

**Comment by tpluscode** [comment]
hey, JSON-LD's linking can't force the correct use. similarly, HTML won't prevent such dead links either. but they will still be links.

**Comment by msporny** [comment]
@dret wrote:
> could you give an example, please? i am still struggling to see that.

Here's one:

```
{
  "@context": {
    "name": "https://schema.org/name",
    "url": {
      "@id": "https://schema.org/url",
      "@type": "@id"
    }
  },
  "name": "Manu Sporny",
  "url": "https://manu.sporny.org/"
}
```

The "url" is a link as specified in the JSON-LD Context, and as defined by the JSON-LD data model, without involving RDF in any way.

@tpluscode wrote:
> JSON-LD's linking can't force the correct use. similarly, HTML won't prevent such dead links either

This is correct, and I would question any definition of hypermedia that requires the enforcement of link liveliness. It was considered at some point that all hypermedia systems should enforce "bi-directional liveliness", that is, that those systems shouldn't allow dead links. One of the breakthroughs that the Web made was allowing dead links, which enabled it to scale in the way it did.

**Comment by msporny** [comment]
@asbjornu wrote:
> If @id can't be guaranteed to be dereferenceable (the specification say SHOULD, not MUST), it isn't really a link, is it? 

The only requirement for hypermedia, afaict, is that a link fits the definition of a URI, which includes URNs, which are not required to be dereferenceable, but can be given the appropriate protocol.

**Comment by dret** [comment]
On 2017-02-01 15:42, Manu Sporny wrote:
> @dret <https://github.com/dret> wrote:
> Here's one:
>
> |{ "@context": { "name": "https://schema.org/name", "url": { "@id":
> "https://schema.org/url", "@type": "@id" } }, "name": "Manu Sporny",
> "url": "https://manu.sporny.org/" } |
>
> The "url" is a link as specified in the JSON-LD Context, and as defined
> by the JSON-LD data model, without involving RDF in any way.

interesting. to me, the "url" is a URL courtesy of schema.org (and i 
would argue that a URL just by itself is not a link, but that's a 
different discussion, and schema.org's definition is not terribly 
helpful in this case).

of course you could come up with an arbitrary number of schemas defining 
link-like concepts, and then use those. but then you're simply using 
RDF's basic model (which i think also has no links): the meaning is 
derived from vocabularies you are using, not from the metamodel within 
which you are using it.

which is why i have for example argued that siren indeed is hypermedia: 
it is RDF-based, but has a specific vocabulary for link representation.

or to use another example: to me, XML clearly is not hypermedia, but 
HTML (let's assume we're talking about XHTML for now) is, because its 
vocabulary defines concepts for representing links. but that does not 
turn XML into a hypermedia format.

**Comment by msporny** [comment]
> because its vocabulary defines concepts for representing links

You are playing with the definition of "link" to make it more restrictive than I would. I believe your definition of "link" is far more restrictive than that used in HTML, for example. I also reject the notion that RDF "has no links".

**Comment by tpluscode** [comment]
> I also reject the notion that RDF "has no links".

Yeah, I agree with you in that too. In RDF you have URI for identifiers everywhere. Assuming they are dereferencable, this makes RDF inherently distributed. A fact which I always mention in this context, Isn't that distributed nature a synonym of links?

**Comment by Conal-Tuohy** [comment]
If I make a respectful suggestion @dret, perhaps you could move this discussion on from terminological dispute into more fruitful terrain by adopting a less schematic approach to describing the software technologies? i.e. don't try to _classify_ JSON-LD (and other technologies) as being _either_ a "hypermedia format" or not, but rather _describe_ the various hypermedia-related functions which it plays. 

It's clear that continuing to say "JSON-LD is not hypermedia" continues to cause puzzlement, because a different interpretation of the term "hypermedia" would place JSON-LD in a different bucket. But your real goal surely is not to place things in buckets but to describe the rich and messy space of hypermedia technology. I think it's a hopeless task to assert your own specialised meaning for terms like "hypermedia", "hypermedia format", "link", etc, which have their own history and are widely used with much broader semantics than those you want to apply here. Better to coin your own distinctive terms; or otherwise to be explicit about the different layers of the hypermedia stack; and avoid appearing to _assign_ complex things exclusively to one or another layer.

**Comment by dret** [comment]
On 2017-02-02 01:35, Conal Tuohy wrote:
> If I make a respectful suggestion @dret <https://github.com/dret>,
> perhaps you could move this discussion on from terminological dispute
> into more fruitful terrain by adopting a less schematic approach to
> describing the software technologies? i.e. don't try to /classify/
> JSON-LD (and other technologies) as being /either/ a "hypermedia format"
> or not, but rather /describe/ the various hypermedia-related functions
> which it plays.

agreed, and thanks for the intervention ;-). and mostly i was calling 
for contributions to the descriptive parts of hyperpedia. selecting 
which technologies to then describe with such a framework is the second 
step, which is why so far, i have not started working on any technology 
descriptions and the goal is to make progress with the descriptive 
framework.

> It's clear that continuing to say "JSON-LD is not hypermedia" continues
> to cause puzzlement, because a different interpretation of the term
> "hypermedia" would place JSON-LD in a different bucket. But your real
> goal surely is not to place things in buckets but to describe the rich
> and messy space of hypermedia technology. I think it's a hopeless task
> to assert your own specialised meaning for terms like "hypermedia",
> "hypermedia format", "link", etc, which have their own history and are
> widely used with much broader semantics than those you want to apply
> here. Better to coin your own distinctive terms; or otherwise to be
> explicit about the layers; and avoid appearing to /assign/ complex
> things exclusively to one or another layer.

my only comment then: the arguments that were made in favor of JSON-LD 
essentially are arguments for RDF, which means that adding JSON-LD would 
imply adding RDF, or more radically, adding RDF would imply adding its 
multitude of serializations, among them JSON-LD. That's probably the 
route to go for now, and we can revisit once there a descriptive 
framework in place and it becomes clear how RDF and its serializations 
fit into it.

**Comment by dret** [comment]
closing by adding RDF and JSON-LD. https://github.com/dret/hyperpedia/commit/26aeb4fd15d29d8972b6c7c7fdd9ff1323fc12c8

**Comment by Conal-Tuohy** [comment]
>  the arguments that were made in favor of JSON-LD
essentially are arguments for RDF, which means that adding JSON-LD would
imply adding RDF, or more radically, adding RDF would imply adding its
multitude of serializations, among them JSON-LD. 

I agree ... and I think aspiring to be "encyclopedic" does imply including everything that's relevant.

> That's probably the
route to go for now, and we can revisit once there a descriptive
framework in place and it becomes clear how RDF and its serializations
fit into it.

I think that's exactly the right approach: get everything in, and then work out how it fits together. I think, apropos of that, that organising the various parts in a dependency graph could be useful. All those RDF vocabularies with hypermedia semantics depend on RDF, RDF depends on URIs, etc, RDF/XML depends on RDF and XML, and XML namespaces, and so on like that. You could still devote most attention to the leaf nodes of that dependency tree, but having the underpinnings there will I think be useful.
